Repository RyanBriggsDev/certify, pull requests merged in 2023-03, with the labels that each got.

#33 Table Component
  src/components/Modal.tsx
  src/components/Table.tsx
  src/lib/utils.ts
  src/pages/api/candidate/index.ts
  src/pages/candidates/index.tsx
  src/pages/courses.tsx
  src/pages/stylesheet.tsx
Labels: front end

#32 Course cards
  package-lock.json
  package.json
  src/components/ContentAlignment/Frame/Content.tsx
  src/components/ContentAlignment/Frame/Nav.tsx
  src/components/Modal.tsx
  src/lib/AlertContext.ts
  src/lib/dates.ts
  src/lib/types.ts
  src/pages/api/course/index.ts
  src/pages/app/index.tsx
  src/pages/app/test.tsx
  src/pages/courses/index.tsx
  src/pages/customers/index.tsx
Labels: front end, new feature

#35 Bug fixes
  src/components/ContentAlignment/Frame/Nav.tsx
  src/components/ContentAlignment/Frame/Sidebar.tsx
Labels: enhancement

#36 Added create candidate page
  src/components/Alert.tsx
  src/lib/schema.ts
  src/pages/candidates/create.tsx
  src/pages/dashboard.tsx
  src/pages/stylesheet.tsx
Labels: front end, new feature

#39 Create Course page /courses/create
  src/components/form/Input.tsx
  src/pages/courses/create.tsx
  src/pages/courses/index.tsx
  src/pages/dashboard.tsx
  src/pages/stylesheet.tsx
Labels: front end, enhancement, new feature

#42 Some basic api fixes
  src/pages/api/course/[id].ts
Labels: bug, back end

#41 Single course page
  src/components/Alert.tsx
  src/components/ContentAlignment/Frame/Content.tsx
  src/components/Headings.tsx
  src/components/Table.tsx
  src/components/headings/H1.tsx
  src/components/headings/H2.tsx
  src/components/headings/H3.tsx
  src/components/headings/H4.tsx
  src/components/headings/H5.tsx
  src/components/headings/H6.tsx
  src/lib/utils.ts
  src/pages/candidates/create.tsx
  src/pages/candidates/index.tsx
  src/pages/courses/[id].tsx
  src/pages/courses/create.tsx
  src/pages/courses/index.tsx
  src/pages/dashboard.tsx
  src/pages/index.tsx
  src/pages/stylesheet.tsx
Labels: front end, new feature

#43 Profile
  src/components/ContentAlignment/Frame/Nav.tsx
  src/components/ContentAlignment/Frame/Sidebar.tsx
  src/components/Protected.tsx
  src/pages/api/profile.ts
  src/pages/candidates/create.tsx
  src/pages/dashboard.tsx
  src/pages/profile.tsx
Labels: back end, front end, new feature

#49 Single candidate page built
  src/components/form/Form.tsx
  src/components/form/Input.tsx
  src/pages/api/candidate/[id].ts
  src/pages/api/candidate/index.ts
  src/pages/candidates/[id].tsx
  src/pages/candidates/index.tsx
Labels: bug, front end, new feature
